apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xrs.example.crossplane.io   # plural + “.” + group
spec:
  group: example.crossplane.io
  names:
    kind: XR                       # the “Kind” of your XR
    plural: xrs                    # plural (lowercase) for the API endpoint
  # scope: Namespaced                # choose Namespaced (or Cluster as needed)
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
              required:
                - region